### PR TITLE
Add docker-compose and link to wiki

### PR DESCRIPTION
**Pull request by rhyslbw**
Adds a `docker-compose.yaml` for a convenient single-host deployment starting point. The wiki has been updated to include minimal setup and run instructions using standard tooling.

Draft until the dependencies can be pinned with a fully working solution. Until then this branch can be considered a test for acceptance of the complete solution.

### CODE REVIEW

**Comment by KtorZ** [comment]
I am getting a lot of errors locally on first try. I need to double-check my postgre configuration but somethings seems a bit off with the volumes :thinking:

**Comment by rhyslbw** [comment]
I had staged this for the nix developers to use it as acceptance criteria. We cannot couple the service state with the node socket in a volume, so the Docker images need to change. I'm working on this

**Comment by KtorZ** [comment]
Yeah, I've been hacking around yesterday and there are a few annoying things with the images as they are right now: 

a) The `node.socket` can't just be easily shared across services because it is a file and mounting files as volumes is kinda tricky with Docker. As a work around, I mounted the whole `/data` and within which happen to also be `/data/node.socket`. Ugly, but does the job for now. 

b) Logs from `cardano-db-sync` are not really user friendly. Forces us to mount a `/tmp` volume in order to access them... when there are logs. I ran into 2 or 3 errors that were simply very cryptic and occurred before the log handlers were even in place. 

c) The `pgpass` file also has to be mounted as a volume, though ideally, I'd rather have this one manage as a secret since in the end, it also contains the postgres credentials.

**Comment by rhyslbw** [comment]
Improvement proposal https://github.com/input-output-hk/cardano-db-sync/issues/26

**Pull request merged**
